### PR TITLE
made changes in contact.html

### PR DESCRIPTION
**Pull request by reerajput930**
Hy these are the changes I have made. ***issue no : #1***

- [x]   It is now connected from email. just replace the demo email with your email id.
- [x]   You'll receive the user data, email, and GitHub account with the help of mailto, if you wish to change that you can do

> Mailto is the only option to connect HTML to the email, however other than that either we have to create the backend or we have to take a third-party subscription to do so.

***Review my branch and merge it.***
and afterward I'll move on to the responsive issue

### CODE REVIEW

**Comment by AnamuddinAhmad** [comment]
@reerajput930 Thank You But till now footer is not responsive..

**Comment by reerajput930** [comment]
Yeah, I ll make it responsive.

**Comment by AnamuddinAhmad** [comment]
@reerajput930  If you don't mind can you reply me on instagram..

**Comment by AnamuddinAhmad** [comment]
@reerajput930 I want to discus about this portfolio.

**Pull request merged**
